import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950`}>
        <div className="min-h-screen w-full flex justify-center">
          <div className="relative flex min-h-screen w-full max-w-[480px] flex-col bg-slate-950 text-white">
            <main className="flex-1 overflow-y-auto px-5 pt-6 pb-32">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
